---
title: "Writing"
toc: true

---

***

### Rain

Date Posted: March 22, 2024

As I’m waiting to get my picture taken in line at the DMV, I remember standing
with my classmates, all of us arranged in a line that lead into the doorway of
the gym, hearing and seeing the flash of the photographer’s camera, and I
remember thinking about my hair, how my mother had spent that morning curling
it, only for the rain to ruin it within the seconds it took for me to get from
bus to school, and I remember how sad I was that rain could ruin such hard
work, that this endeavor my mother took on, despite already being late for
work, could be erased with such ease, and I remember thinking – what else could
the rain make disappear, could it erase me from existence, and if it did, would
it take the memories of me with it, would my mother remember where the burn on
her forefinger had come from, that I had been the one to bump the curling iron
into her hand that morning, that she used to have a daughter, with beautifully
curled hair, before the rain washed her away.

“Next!”

I approach the desk and the attendant instructs me to stand on a red-duct tape
X that had been stuck to the floor. I feel a strange, intense sympathy for this
X – being stepped on each day, repeatedly, only to be ripped up and replaced
once your edges start to lift and you can no longer stick like they want you to
– what a miserable existence.

She tells me that I can smile if I wish – I don’t. I rarely wish to smile, to
feel my face move against my will, an involuntary action that so many people
seem to find enjoyable. Why, I’ve always wondered, do people enjoy something so
out of their control?

I’m flashed with a blinding light, and I try to keep my eyes open – I fail. My
eyes squeeze shut, trying to shield themselves from the painful assault. And I
hate it – this lack of control I have over my own body – that my eyes can close
against my will, even though keeping them open should be _such_ a simple task. I
try to coax my eyes to open, telling them the offending light is gone, that
it's safe now – they listen, but I can feel their hesitance. The lady, filling
out papers, doesn’t even look up as she speaks.

“Your new license will arrive in the mail within three to five business days.
Have a great day.”

Her bored tone irritates me. I _know_ she’s just doing her job, going through the
motions. To her, someone losing control of their eyes is an everyday
occurrence. But doesn’t she know that the eyes are just the first step? Can she
not see my control being pulled further and further from my body with every
second?

My body turns and walks towards the door, its ears picking up the muffled _Next!_
that comes from the lady’s mouth. Another person steps forward to lose control
of their eyes – the first step. As my body passes through the doorway, I feel
the rain hit its skin and I think – _This is it. The rain is here to wash me
away._

I see my mother at her weekly nail appointment, the woman next to her asking
about the scar on her forefinger. I see her stare at her finger, at that small,
insignificant patch of scar tissue. I see her shrug and tell the woman she has
no clue where it came from. I see her walking through the front door of my
childhood home. I see her pass by walls covered in pictures – pictures absent
of me. I see her pass by my bedroom door, the plaque with my name on it no
longer hanging from a bent nail I had poorly hammered into the wood – an act
that got me grounded for a week. I see her walk into her bathroom and open the
drawer under the sink. I see her reach for her hairbrush, passing over the same
curling iron that gave her that scar.

But the rain doesn't wash me away – instead, it performs a miracle.

I feel the force that has been steadily pulling on my control lose its grip,
slickened by the rain. I feel my control slip back into its rightful place. _I_
close my eyes. _I_ tilt my head back. _I_ savor the feeling of the rain on my skin
– each drop leaving a cool, damp line behind until my entire body is covered in
cool, damp lines. And for once the rain doesn’t seem so bad. Sure, it washes
things away, and sometimes those things are things you want to keep, but
sometimes the rain does you a favor, and the things it washes away are the
things you so desperately want to be rid of.

***

### The Void

Date Posted: March 22, 2024

I don’t know what triggered it. One minute I’m sitting in my favorite café,
people-watching through the storefront window – and the next, I’m here. Here
being _The Void_, as I’ve taken to calling it. I’ve been sent to _The Void_ since
childhood, each visit caused by some sort of trigger I have yet to put my
finger on.

Despite my regular visits, I always struggle to find my way around. This place
is so devoid of light you would think you were floating in an abyss of
nothingness if you could not feel the floor beneath your feet. But it’s not a
place of nothingness, in fact it’s filled with never-ending clutter. At least,
I assume it’s never-ending – I’ve never reached the end. Each time I’m thrown
into _The Void_, the layout changes, no matter if the visits are weeks apart or
merely hours. It’s almost as though _The Void_ is a living entity, always
changing.

I try to ground myself by taking off my shoes and socks, pushing my feet into
the floor, the familiar cold seeping from the tiles and into my feet. I slide
across the floor and extend my arms out in front of me, moving slowly. I’ve
injured myself too many times trying to rush. I leave my shoes and socks behind.

I come into contact with what feels like fabric, and I run my hands over the
surface, trying to figure out what this object is. It seems to be a couch, with
lumpy cushions and wooden accents… I think. Within _The Void_, you can never be
sure if what you’re feeling is _actually_ what you’re feeling.

I find the edge of the “couch” and move past it, arms reaching out to feel the
next object. I continue this maneuver over and over again – it’s the only thing
I _can_ do.

Then the pressure starts to build – that unbearable pressure that always starts
as soon as the maneuver becomes easy. While _The Void_ always begins as some
impossible task, after a time it almost becomes enjoyable.

This pressure is the signal that I’m about to be ejected back into the “real
world” – and, at this point, I don’t know if I want to go back. But I’m never
given a choice. The pressure continues to build until I’m no longer able to
stand, pinned to the tile floor. _The Void_ starts to shake from the pressure,
all its contents shaking with it – me included. I close my eyes and try to
outlast the shaking.

:::{.center}
\***
:::

“Excuse me,” the voice makes me open my eyes. The barista is now the one
shaking me, her hand on my shoulder. She’s looking at me, concerned. “Are you
alright?”

“I’m fine. Thank you, though.”

“Okay. Well, we’re closing so…” She looks as though she’s waiting for me to
scream at her – the dangers of customer service.

I look outside only to find my reflection staring back at me, the window having
gone black with the night. It had been bright outside when I was sent into The
Void – a whole day stolen by _The Void_. I nod, attempt to give her a smile, and
leave.
