project:
  type: website

website:
  title: "Haylee Pierce"
  back-to-top-navigation: true
  navbar:
    title: HP
    right: 
      - text: "Home"
        href: home.qmd
      - text: "About"
        href: about.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Contact"
        href: contact.qmd
  page-footer:
    border: false
    background: primary
    left: "Copyright 2025, Haylee Pierce"
    right:
      - icon: github
        href: https://github.com/hayleepierce
    

format:
  html:
    theme: minty
    css: styles.css
    toc: false