project:
  type: website
  render:
    - "*.qmd"
    - "!_resources/"
  preview:
    port: 5550
    browser: false
    watch-inputs: true
    navigate: false

website:
  title: "Home"
  page-navigation: true
  favicon: "icons/logo.png"
  site-url: https://hayleepierce.netlify.app
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - href: about_me/about.qmd
        text: About Me
      - href: projects/index.qmd
        text: Projects
  page-footer:
      center:
          - text: Source Code
            href: https://github.com/hayleepierce/hayleepierce.netlify.app
          - text: Report An Issue
            href: https://github.com/hayleepierce/hayleepierce.netlify.app/issues/new

format:
  html:
    theme: 
      - cosmo
      - style/custom.scss
    mainfont: sans-serif
    fontsize: 1.5em
    fontcolor: black
    backgroundcolor: white
    css: style/styles.css
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
