---
author: Haylee Pierce
title: SE4 - "Knowledge Sharing"
date: '09/27/2023'
date-format: MM/DD/YYYY
categories: [post, SE, Week 4]
description: <em>My week 4 professional précis for Software Engineering at Google.</em>
---

::: {.justify}

The "Knowledge Sharing" chapter of _Software Engineering_ discusses the importance of spreading information to your peers. Often there is a small bunch of people who have the majority of the knowledge, while the rest of the group has minimal knowledge. This makes it so that a small number of people do most of the work and carrys most of the weight for projects. The time it takes to finish a project is often greatly increased because of a lack of knowledge. Should the "knowledge havers" share their information with those who have minimal knowledge, the workload could be spread out and projects would take less time to complete. 

The importance of documentation is also touched on. When new people join a team that has already been working on projects together for years, they have a lot of knowledge to catch up on. This can feel very overwhelming. Not only should their co-workers share knowledge with them, documentation should be created to make this information easier to gather. This documentation could be in the form of code comments, README files, videos, etc. All the documentation should be located in an easy to find place.

We should implement many of the practices discussed in this chapter. Many of us has staggering levels of knowledge; we have some "knowledge havers" and some with minimal levels of knowledge. Those with the knowledge should share it and those with minimal knowledge should ask questions to gain information. We need to give a good amount of time to documentation, as well. The programs we are developing will hopefully still be used in the furture and those doing the up-keep years later will appreciate good documention.

:::

{{< include /_back-blog.qmd >}}