---
author: Haylee Pierce
title: DB4 - "Statistical Debugging"
date: '12/8/2023'
date-format: MM/DD/YYYY
categories: [Debugging Book, Week 13]
description: <em>My week 13 professional précis for Debugging Book.</em>
---

::: {.justify}

The ["Statistical Debugging"](https://www.debuggingbook.org/html/StatisticalDebugger.html) chapter of _Debugging Book_ introduces the concepts of _statistical debugging_, which is the idea that specific events that occur during execution could be _statistically correlated_ with failures.

To determine what exectutions are correlated with failure, the _coverage_ information needs to be collected. The coverage information reveals what lines of code were executed. Below is an example output of the function `code_with_coverage` from the chapter:

```python
   1 * def remove_html_markup(s):  # type: ignore
   2 *     tag = False
   3 *     quote = False
   4 *     out = ""
   5   
   6 *     for c in s:
   7 *         if c == '<' and not quote:
   8               tag = True
   9 *         elif c == '>' and not quote:
  10               tag = False
  11 *         elif c == '"' or c == "'" and tag:
  12               quote = not quote
  13 *         elif not tag:
  14 *             out = out + c
  15   
  16 *     return out
```

Each line of the `remove_html_markup()` function is displayed with a `*` indicating that line was executed.

After determining what lines of code are being executed, the failures can be connected to specific lines of code. For example, if an error occured with the above execution, line 12 would not have caused because it was never executed. To find what actually cause the error, the code will have to be executed several times, with several different inputs; this will provide more information about when the errors occur and what lines are run.

The content from the chapter could be used within the debugging process of chasten and cellveyor. When debugging, the coverage information can be gathered; allowing us to determine the correlation between what code was executed and what error occured.
:::

{{< include /_back-blog.qmd >}}