---
author: Haylee Pierce
title: SE5 - "Engineering for Equity"
date: '10/20/2023'
date-format: MM/DD/YYYY
categories: [post, SE, Week 5]
description: <em>My week 5 professional précis for Software Engineering at Google.</em>
---

::: {.justify}

The ["Engineering for Equity"](https://abseil.io/resources/swe-book/html/ch04.html) chapter of _Software Engineering_ covers the importance of equity within software engineering.

Software engineering teams often focus solely on the performance and excellence of their team and projects; therefore, the practices of equity end up being put on the back burn, or even completely forgotten. This leads to a team and project that does not take into account minorities and diversity. The team members may have a hidden bias, or simply a lack of knowledge, that would lead them to exclude a demographic from the user base of the team's tool. Striving to have a diverse team of individuals on the team helps to mitigate this exclusion. It is extremely important to ensure all demographics are thought about in the development of a tool; including race, gender, ethnicity, education level, etc. Not only will this increase the number of users the tool has, but it will also ensure that the users do not feel discriminated against.

While our team is doing well in the diversity aspect, we have yet to deeply discuss the user base for our project. We are all aware that the professors and students are going to be using our tools, but we have not really thought about how we can directly cater to them. The completion of the project has become the most important task for us, causing us to put the user base on the back burner. How can we make this tool easier for them to use? What features could be added to the tool specifically for the users?

:::

{{< include /_back-blog.qmd >}}