---
author: Haylee Pierce
title: FB2 - "Code Coverage"
date: '09/13/2023'
date-format: MM/DD/YYYY
categories: [post, FB, Week 2]
description: <em>My week 2 professional précis for Fuzzing Book.</em>
---

::: {.justify}

This chapter of _Fuzzing Book_ ("Code Coverage") discusses the different forms of testing that you can use to increase code coverage. One form of testing is **black-box testing**; testing the specific behavior of a program. Black-box testing is useful, but it does not cover nearly as much code as white-box testing. **White-box testing** consists of coverage criteria, such as statement coverage and branch coverage. This means that every statement of code must be ran through a test. While white-box testing has excellent coverage, it will not find any missing functionalities of the program.

The chapter includes the use of _tracing functions_, which could help us greatly in our testing and debuging of Chasten. When writing test cases for code we should make use of tracing, as it will help us know where in the code the error occured.

:::

{{< include /_back-blog.qmd >}}